name: 'Zip Action'
description: 'Create a .zip archive'
inputs:
  glob:  # id of input
    description: 'Glob (or multiple globs separated by a single space) to collect files for the archive'
    required: true
    default: '**'
  target:  # id of input
    description: 'Output path (e.g. target/release.zip)'
    required: true
    default: 'release.zip'
  cwd:  # id of input
    description: 'Base directory for input files'
    required: true
    default: './'
runs:
  using: 'node12'
  main: 'index.js'
